# Generated by Django 3.0.6 on 2020-06-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='9800000000', max_length=14, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
