# Generated by Django 3.0.6 on 2020-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activateemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
