# Generated by Django 3.0.6 on 2020-05-11 15:12

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('is_active', models.BooleanField(default=True)),
                ('hard_title', models.CharField(max_length=1000)),
                ('soft_title', models.CharField(max_length=1000)),
                ('title_image', models.ImageField(upload_to=blog.models.image_upload_path)),
                ('post_body', models.TextField()),
                ('flags', models.PositiveIntegerField(blank=True, null=True)),
                ('slug_name', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('comments', models.ManyToManyField(blank=True, null=True, to='blog.Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post ',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug_name', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post tag',
                'verbose_name_plural': 'post tags',
            },
        ),
        migrations.CreateModel(
            name='SubPostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('is_active', models.BooleanField(default=True)),
                ('inter_post_sequence', models.PositiveIntegerField(default=1)),
                ('inter_post_heading', models.CharField(max_length=200)),
                ('inter_post_content', models.TextField()),
                ('highlight_content', models.TextField(blank=True, null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to=blog.models.subpostcontentimage)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post Heading ',
                'verbose_name_plural': 'Blog Posts Headings',
                'ordering': ['inter_post_sequence'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='has_tags',
            field=models.ManyToManyField(to='blog.Tags'),
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Blog Categories')),
                ('slug_name', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main Blog Category',
                'verbose_name_plural': 'Main Blog categories',
            },
        ),
    ]
