# Generated by Django 3.0.6 on 2020-05-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subpostlistelements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubPostListElements',
        ),
    ]
