# Generated by Django 3.0.6 on 2020-05-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_listelements_subpostlistelements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listelements',
            options={'verbose_name': 'List Element ', 'verbose_name_plural': 'List Elements'},
        ),
        migrations.AlterModelOptions(
            name='subpostlistelements',
            options={'verbose_name': 'Sub Post List Element', 'verbose_name_plural': 'Sub Post List Elements'},
        ),
    ]
