# Generated by Django 3.0.6 on 2020-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200515_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listelements',
            old_name='elements',
            new_name='element',
        ),
        migrations.AlterField(
            model_name='listelements',
            name='sub_elements',
            field=models.ManyToManyField(related_name='_listelements_sub_elements_+', to='blog.ListElements'),
        ),
    ]
