# Generated by Django 3.0.6 on 2021-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_sitecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Website Categories'),
        ),
    ]
