# Generated by Django 3.0.6 on 2021-06-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
