# Generated by Django 3.0.6 on 2021-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalab', '0002_auto_20210629_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='content',
            field=models.TextField(),
        ),
    ]
