# Generated by Django 3.0.6 on 2021-07-02 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datalab', '0003_auto_20210629_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharepost',
            options={'ordering': ['-created_on']},
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Category Created Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Category Updated Date')),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('codeContent', models.TextField(blank=True, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalab.SharePost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
